# Generated by Django 3.0.8 on 2020-07-19 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('tshirt', 'tshirt'), ('shirt', 'shirt'), ('jacket', 'jacket'), ('sweatshirt', 'sweatshirt'), ('underwear', 'underwear'), ('shorts', 'shorts'), ('jeans', 'jeans'), ('pants', 'pants'), ('socks', 'socks'), ('mask', 'mask'), ('towel', 'towel'), ('bedsheet', 'bedsheet'), ('etc', 'etc')], max_length=20)),
                ('color', models.CharField(choices=[('white', 'white'), ('grey', 'grey'), ('black', 'black'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('datebought', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
